language: c
compiler: clang
before_install:
- sudo apt-get install -qq apt-transport-https ca-certificates
- curl https://letsencrypt.org/certs/isrgrootx1.pem.txt | sudo tee /etc/ssl/certs/ca-certificates/isgrootx1.pem
- sudo update-ca-certificates
- curl https://raw.githubusercontent.com/bbcarchdev/bbcarchdev-keys/main/bbcarchdev-apt.asc | sudo apt-key add -
- echo "deb https://apt.bbcarchdev.net/debian stable main port dev stage live" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install -qq automake autoconf libtool pkg-config
- sudo apt-get install -qq libedit-dev uuid-dev liburi-dev libmysqlclient-dev libpq-dev libsqlite3-dev
before_script:
- autoreconf -f -i
